--- 
- name: Deploy app in new namespace
  hosts: localhost
  tasks:  
    - name: Create a k8s namespace
      k8s:
         name: testing
         api_version: v1 
         kind: Namespace
         state: present   
         kubeconfig: ~/kubeconfing_eks-cluster

    - name: Deploy nginx app 
      k8s: 
        src: ~/Documents/nginx-confing.yaml
        state: present 
        kubeconfig: ~/kubeconfing_eks-cluster
        namespace: testing



    




