--- 

- name: Install java and net tools
  hosts: 159.89.1.54
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes  force_apt_get=yes cache_valid_time=3600
    - name: Install java 8 
      apt : name=openjdk-8-jre-headless
    - name: Install net-tools
      apt : name=net-tools

- name: Install Nexus
  hosts: 159.89.1.54
  tasks:
    - name: Download Nexus
      get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz 
        dest: /opt/      
      register: download_result
    - name: Extract Nexus
      unarchive:
        src: "{{ download_result.dest }}"
        dest: /opt/
        remote_src: yes
    - name: Rename Nexus folder
      command: mv /opt/nexus-* /opt/nexus    

- name: Create nexus user to own nexus folders
  hosts: nexus_server
  tasks:
    - name: Ensure group nexus exists
      ansible.builtin.group: 
        name: nexus
        state: present
    - name: Create nexus user
      ansible.builtin.user: 
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      ansible.builtin.file: 
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes    
    - name: Make nexus user owner of sonatype-work folder
      ansible.builtin.file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: nexus_server
  become: True
  become_user: nexus     
  tasks:
    - name: Set run_as_user nexus
      ansible.builtin.lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      ansible.builtin.command: /opt/nexus/bin/nexus start

- name: Verify nexus running
  hosts: nexus_server
  tasks:
    - name: Check with ps
      ansible.builtin.shell: ps aux | grep nexus
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}
    - name: Wait one minute
      ansible.builtin.pause:
        minutes: 1
    - name: Check with netstat
      ansible.builtin.shell: netstat -plnt
      register: app_status
    - ansible.builtin.debug: msg={{app_status.stdout_lines}}