- name: Copy docker compose
  copy:
    src: /Users/ahmedalaa/Demo-projects/Bootcamp/Exercises/bootcamp-java-mysql-project/docker-compose-full.yaml
    dest: /home/ahmedalaa/docker-compose.yaml

- name: Docker login
  docker_login: 
    registry_url: https://index.docker.io/v1/
    username: ahmedalaa
    password: "{{ docker_password }}"

- name: Start container from compose
  docker_compose: 
    project_src: /home/ahmedalaa